/*
 * User Manager API
 *
 * Description of a user manager API
 *
 * API version: 1.0.0
 * Contact: lars@lgblaumeiser.de
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */
// SPDX-FileCopyrightText: 2022 Lars Geyer-Blaumeiser <lars@lgblaumeiser.de>
// SPDX-License-Identifier: MIT
package main

import (
	"log"
	"net/http"

	_ "github.com/lgblaumeiser/usermanager/statik"
	"github.com/rakyll/statik/fs"

	"github.com/lgblaumeiser/usermanager/rest"
	"github.com/lgblaumeiser/usermanager/service"
	"github.com/lgblaumeiser/usermanager/store"
)

func main() {
	log.Printf("Server started")

	store := store.CreateMemoryStore()
	userService := service.NewUserService(store)

	InfrastructureApiController := rest.NewInfrastructureApiController(&userService)
	UsersApiController := rest.NewUsersApiController(&userService)

	router := rest.NewRouter(InfrastructureApiController, UsersApiController)

	statikFS, err := fs.New()
	if err != nil {
		panic(err)
	}

	staticServer := http.FileServer(statikFS)
	sh := http.StripPrefix("/openapi/", staticServer)
	router.PathPrefix("/openapi/").Handler(sh)

	log.Fatal(http.ListenAndServe(":19749", router))
}
