#!/bin/sh
./openapi-generator-cli \
    generate \
    -i ../../ProjectTimeManager2.Api/user-mgr.yaml \
    -g go-server \
    -o .. \
    -v \
    --additional-properties=onlyInterfaces=false,packageName=rest,serverPort=19749,sourceFolder=rest

cp -v ../api/openapi.yaml ../openapi/user_manager.yaml
cp -v ../README.md ../rest/Readme.md
git checkout HEAD -- ../README.md
