/*
 * User Manager API
 *
 * Description of a user manager API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rest

import (
	"context"
	"net/http"
	"os"
)



// InfrastructureApiRouter defines the required methods for binding the api requests to a responses for the InfrastructureApi
// The InfrastructureApiRouter implementation should parse necessary information from the http request,
// pass the data to a InfrastructureApiServicer to perform the required actions, then write the service results to the http response.
type InfrastructureApiRouter interface { 
	Backup(http.ResponseWriter, *http.Request)
	License(http.ResponseWriter, *http.Request)
	Restore(http.ResponseWriter, *http.Request)
}
// UsersApiRouter defines the required methods for binding the api requests to a responses for the UsersApi
// The UsersApiRouter implementation should parse necessary information from the http request,
// pass the data to a UsersApiServicer to perform the required actions, then write the service results to the http response.
type UsersApiRouter interface { 
	AuthenticateUser(http.ResponseWriter, *http.Request)
	ChangePassword(http.ResponseWriter, *http.Request)
	ChangeRoles(http.ResponseWriter, *http.Request)
	DeleteUser(http.ResponseWriter, *http.Request)
	RegisterUser(http.ResponseWriter, *http.Request)
}


// InfrastructureApiServicer defines the api actions for the InfrastructureApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type InfrastructureApiServicer interface { 
	Backup(context.Context) (ImplResponse, error)
	License(context.Context) (ImplResponse, error)
	Restore(context.Context, *os.File) (ImplResponse, error)
}


// UsersApiServicer defines the api actions for the UsersApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type UsersApiServicer interface { 
	AuthenticateUser(context.Context, UserData) (ImplResponse, error)
	ChangePassword(context.Context, UserData) (ImplResponse, error)
	ChangeRoles(context.Context, UserData) (ImplResponse, error)
	DeleteUser(context.Context, UserData) (ImplResponse, error)
	RegisterUser(context.Context, UserData) (ImplResponse, error)
}
