/*
 * User Manager API
 *
 * Description of a user manager API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rest

import (
	"context"
	"net/http"
	"errors"
	"os"
)

// InfrastructureApiService is a service that implements the logic for the InfrastructureApiServicer
// This service should implement the business logic for every endpoint for the InfrastructureApi API.
// Include any external packages or services that will be required by this service.
type InfrastructureApiService struct {
}

// NewInfrastructureApiService creates a default api service
func NewInfrastructureApiService() InfrastructureApiServicer {
	return &InfrastructureApiService{}
}

// Backup - Create a backup of the database
func (s *InfrastructureApiService) Backup(ctx context.Context) (ImplResponse, error) {
	// TODO - update Backup with the required logic for this service method.
	// Add api_infrastructure_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, *os.File{}) or use other options such as http.Ok ...
	//return Response(200, *os.File{}), nil

	//TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	//return Response(401, nil),nil

	//TODO: Uncomment the next line to return response Response(403, {}) or use other options such as http.Ok ...
	//return Response(403, nil),nil

	//TODO: Uncomment the next line to return response Response(500, string{}) or use other options such as http.Ok ...
	//return Response(500, string{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Backup method not implemented")
}

// License - Returns the attribution information on the used Open Source Software
func (s *InfrastructureApiService) License(ctx context.Context) (ImplResponse, error) {
	// TODO - update License with the required logic for this service method.
	// Add api_infrastructure_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, string{}) or use other options such as http.Ok ...
	//return Response(200, string{}), nil

	//TODO: Uncomment the next line to return response Response(500, string{}) or use other options such as http.Ok ...
	//return Response(500, string{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("License method not implemented")
}

// Restore - Restore a backup and replace existing database
func (s *InfrastructureApiService) Restore(ctx context.Context, body *os.File) (ImplResponse, error) {
	// TODO - update Restore with the required logic for this service method.
	// Add api_infrastructure_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(400, string{}) or use other options such as http.Ok ...
	//return Response(400, string{}), nil

	//TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	//return Response(401, nil),nil

	//TODO: Uncomment the next line to return response Response(403, {}) or use other options such as http.Ok ...
	//return Response(403, nil),nil

	//TODO: Uncomment the next line to return response Response(500, string{}) or use other options such as http.Ok ...
	//return Response(500, string{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Restore method not implemented")
}
