/*
 * User Manager API
 *
 * Description of a user manager API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rest

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// UsersApiController binds http requests to an api service and writes the service results to the http response
type UsersApiController struct {
	service UsersApiServicer
	errorHandler ErrorHandler
}

// UsersApiOption for how the controller is set up.
type UsersApiOption func(*UsersApiController)

// WithUsersApiErrorHandler inject ErrorHandler into controller
func WithUsersApiErrorHandler(h ErrorHandler) UsersApiOption {
	return func(c *UsersApiController) {
		c.errorHandler = h
	}
}

// NewUsersApiController creates a default api controller
func NewUsersApiController(s UsersApiServicer, opts ...UsersApiOption) Router {
	controller := &UsersApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all of the api route for the UsersApiController
func (c *UsersApiController) Routes() Routes {
	return Routes{ 
		{
			"AuthenticateUser",
			strings.ToUpper("Post"),
			"/users/authenticate",
			c.AuthenticateUser,
		},
		{
			"ChangePassword",
			strings.ToUpper("Put"),
			"/users",
			c.ChangePassword,
		},
		{
			"ChangeRoles",
			strings.ToUpper("Patch"),
			"/users",
			c.ChangeRoles,
		},
		{
			"DeleteUser",
			strings.ToUpper("Delete"),
			"/users",
			c.DeleteUser,
		},
		{
			"RegisterUser",
			strings.ToUpper("Post"),
			"/users",
			c.RegisterUser,
		},
	}
}

// AuthenticateUser - Authenticate a registered user by password, returns a jwt token
func (c *UsersApiController) AuthenticateUser(w http.ResponseWriter, r *http.Request) {
	userDataParam := UserData{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&userDataParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertUserDataRequired(userDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.AuthenticateUser(r.Context(), userDataParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ChangePassword - Change the password of the user, authentication provided either by token of user or of an admin
func (c *UsersApiController) ChangePassword(w http.ResponseWriter, r *http.Request) {
	userDataParam := UserData{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&userDataParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertUserDataRequired(userDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ChangePassword(r.Context(), userDataParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ChangeRoles - Change roles of user, admin roles can only be changed by an admin
func (c *UsersApiController) ChangeRoles(w http.ResponseWriter, r *http.Request) {
	userDataParam := UserData{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&userDataParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertUserDataRequired(userDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ChangeRoles(r.Context(), userDataParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// DeleteUser - Delete a user and all its data from the database
func (c *UsersApiController) DeleteUser(w http.ResponseWriter, r *http.Request) {
	userDataParam := UserData{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&userDataParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertUserDataRequired(userDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.DeleteUser(r.Context(), userDataParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// RegisterUser - Register a new user, needs no authentication
func (c *UsersApiController) RegisterUser(w http.ResponseWriter, r *http.Request) {
	userDataParam := UserData{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&userDataParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertUserDataRequired(userDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.RegisterUser(r.Context(), userDataParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
