/*
 * User Manager API
 *
 * Description of a user manager API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rest

//Implementation response defines an error code with the associated body
type ImplResponse struct {
	Code int
	Body interface{}
}
