/*
 * User Manager API
 *
 * Description of a user manager API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rest

type UserData struct {

	Username string `json:"username,omitempty"`

	Password string `json:"password,omitempty"`

	Newroles []string `json:"newroles,omitempty"`

	Obsroles []string `json:"obsroles,omitempty"`
}

// AssertUserDataRequired checks if the required fields are not zero-ed
func AssertUserDataRequired(obj UserData) error {
	return nil
}

// AssertRecurseUserDataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UserData (e.g. [][]UserData), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUserDataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUserData, ok := obj.(UserData)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUserDataRequired(aUserData)
	})
}
