/*
 * User Manager API
 *
 * Description of a user manager API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rest

type UserIdentity struct {

	Userid string `json:"userid,omitempty"`
}

// AssertUserIdentityRequired checks if the required fields are not zero-ed
func AssertUserIdentityRequired(obj UserIdentity) error {
	return nil
}

// AssertRecurseUserIdentityRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UserIdentity (e.g. [][]UserIdentity), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUserIdentityRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUserIdentity, ok := obj.(UserIdentity)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUserIdentityRequired(aUserIdentity)
	})
}
